### PR TITLE
make user.editGroups depending on viewHiddenGroups

### LINKED ISSUE #149: edit a user without "view hidden group bages" permission can break membership of the user
[discuss ref](https://discuss.flarum.org/d/26218-group-membership-unstable-behavior/5)

## Bug Report

**Current Behavior**
When a user has the `edit users` permission but doesn't have the `view hidden group badges` one, he can involuntary kick off users from group with a hidden badge simply by add them or remove them to/from an other group. 

**Steps to Reproduce**
1. make 3 groups and 2 users
        group A has the `Edit user groups` permission but doesn't have the `View hidden group badges` one
        group B has the `Hide on forum` attribute
        group C is a control group without special attribute nor permission
2. add `@user1` to group A (can edit user groups) and `@user2` to group B (hidden badge)
3. with `@user1`, edit `@user2` and add him to group C.
4. `@user2` is kicked off the group B 

**Expected Behavior**
`@user2` should remains into group B.

**Environment** 
nightly

### LINKED ISSUE #2610: edit a user without "view hidden group bages" permission can break membership of the user
[discuss ref](https://discuss.flarum.org/d/26218-group-membership-unstable-behavior/5)

## Bug Report

**Current Behavior**
When a user has the `edit users` permission but doesn't have the `view hidden group badges` one, he can involuntary kick off users from group with a hidden badge simply by add them or remove them to/from an other group. 

**Steps to Reproduce**
1. make 3 groups and 2 users
        group A has the `Edit user groups` permission but doesn't have the `View hidden group badges` one
        group B has the `Hide on forum` attribute
        group C is a control group without special attribute nor permission
2. add `@user1` to group A (can edit user groups) and `@user2` to group B (hidden badge)
3. with `@user1`, edit `@user2` and add him to group C.
4. `@user2` is kicked off the group B 

**Expected Behavior**
`@user2` should remains into group B.

**Environment** 
nightly

### PR DESCRIPTION
**Pull request by ornanovitch**
**Fixes flarum/issue-archive#149**

**Changes proposed in this pull request:**

 make user.editGroups depending on viewHiddenGroups

**Reviewers should focus on:**

 is it that simple?

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.

### CODE REVIEW

**Review by SychO9 — APPROVED** [review]
Thanks for the PR!

I was unsure if we did anything else on the backend for permissions relying on others, but it seems to just be a helper on the frontend 🤔

**Review by davwheat — APPROVED** [review]

**Comment by Ornanovitch** [comment]
Thanks for approving :) 

As it's more a fix than a feature, could it be merge for 1.0.5 ?

**Comment by luceos** [comment]
Wouldn't it have been more logical to make the backend responsible for looping over the groups that are not visible and locking them, while updating those that are visible and have been changed?

Because now we require a permission for another permission to work. I can imagine situations where groups can be hidden (like authorative users) but mods should still be allowed to upgrade simple member groups.  @jordanjay29 a penny for your thoughts.

**Comment by SychO9** [comment]
@luceos the plan was to go with https://github.com/flarum/core/issues/2610#issuecomment-840677323 and have this done temporarily.

though I don't have any strong opinions on this, feel free to re-open the issue.

**Pull request merged**
