### PR TITLE
chore: unify JS actions into one (rewritten `flarum/action-build`)

### PR DESCRIPTION
**Pull request by SychO9**
**Relies on https://github.com/flarum/action-build/pull/10**

**Changes proposed in this pull request:**
Unifies all frontend workflows into one.

**Necessity**

- [x] Has the problem that is being solved here been clearly explained?
- [x] If applicable, have various options for solving this problem been considered?
- [x] For core PRs, does this need to be in core, or could it be in an extension?
- [x] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).
- [x] Core developer confirmed locally this works as intended.
- [x] Tests have been added, or are not appropriate here.

### CODE REVIEW

**Comment by SychO9** [comment]
Tested on a single extension repository to make sure things are still good on that end ✅

**Comment by SychO9** [comment]
Bundlewatch is disabled for now since we use a single frontend workflow. Maybe we can specifically have it only measure core dist files, or if possible all dist files at once?

**Comment by davwheat** [comment]
I think disabling Bundlewatch for now is the best. We can look into re-enabling it later.

**Comment by davwheat** [comment]
Rebased to (hopefully) pass PHP tests.

**Review by davwheat — APPROVED** [review]

**Comment by SychO9** [comment]
Here goes nothing..

**Pull request merged**
