### PR TITLE
Jest Testing Configuration

### LINKED ISSUE #424: Set up frontend testing framework

### PR DESCRIPTION
**Pull request by askvortsov1**
Fixes https://github.com/flarum/core/issues/245

This is planned for the beta 15 release cycle.

This PR sets up the jest framework for frontend unit tests. In order to avoid hacking in babel config, we're making core js an es6 module. Only change for now is renaming webpack config (which will no longer be necessary when webpack 5 comes out).

REMAINING WORK:
- Typescript support is currently problematic: when `export default` is used, ts-jest sees this as exporting an object with a key called default. Also, remove the console.log (I included this for now so reviewers can see what's up)
- Revert https://github.com/flarum/core/pull/2298/commits/783f36c3b38ce121c02cc15b7f00aaf6c384dbf0 before merging (we can keep for now while we're testing)

### CODE REVIEW

**Review by franzliedke — COMMENTED** [review]
Once #2311 is merged, we should probably add another badge to the README in this PR here. :grin:

**Review by franzliedke — APPROVED** [review]
Merge it, merge it! Tests are a multiplier. 👏🏼 😉

**Comment by davwheat** [comment]
> This is planned for the beta 15 release cycle.

*Sweats profusely*

**Comment by askvortsov1** [comment]
Ah, I forgot about this one for a bit. The whole ".default" requirement for TypeScript is problematic and confusingly inconsistent though. However, I suspect (and really hope!) that's caused by a config issue. Will dig deeper.

**Comment by davwheat** [comment]
What's the default issue?

**Comment by askvortsov1** [comment]
> Typescript support is currently problematic: when export default is used, ts-jest sees this as exporting an object with a key called default. Also, remove the console.log (I included this for now so reviewers can see what's up)

See the code: for the typescript test case, we need to import, then call `.default` on the imported stuff

**Comment by davwheat** [comment]
Hmmm... In my recent project I didn't need to do this. I think Jest supports TS properly now.

**Comment by askvortsov1** [comment]
> Hmmm... In my recent project I didn't need to do this. I think Jest supports TS properly now.
> 
> https://github.com/davwheat/let-me-really-google-that-for-you/blob/main/__tests__/ErrorBoundary.test.js

I'm making a new branch, that will be cleaner.

**Comment by askvortsov1** [comment]
> Hmmm... In my recent project I didn't need to do this. I think Jest supports TS properly now.
> 
> https://github.com/davwheat/let-me-really-google-that-for-you/blob/main/__tests__/ErrorBoundary.test.js

Just one problem with that. From https://jestjs.io/docs/getting-started#using-typescript:

> However, there are some caveats to using TypeScript with Babel. Because TypeScript support in Babel is purely transpilation, Jest will not type-check your tests as they are run. If you want that, you can use ts-jest instead, or just run the TypeScript compiler tsc separately (or as part of your build process).

**Comment by davwheat** [comment]
We should probably use `tsc`. There are some pretty big issues with core surrounding type-checking last time I tried it which we should probably fix.

**Pull request closed without merging**
