### PR TITLE
Search Refactor and Extenders

### LINKED ISSUE #2071: Guest users can't load more posts on profiles
## Bug Report

**Current Behavior**
When browsing forums as a guest, the "Load More" button for posts is not shown on user profiles, however if you log in and scroll to the bottom of posts on a profile, the option is shown. 

Occurs on discuss.flarum.org

### PR DESCRIPTION
**Pull request by askvortsov1**
**Fixes part of flarum/framework#1891 **
Fixes flarum/framework#2071 
Moves towards flarum/issue-archive#286, flarum/issue-archive#443, probably others
Implements my ideas from https://github.com/flarum/core/issues/1355#issuecomment-605503004

**Changes proposed in this pull request:**
- [x] Bring UserSearcher and DiscussionSearcher under a common, extendable system
- [x] Refactor ListPostsController to use this same system
- [x] Add a search extender and integration tests
- [x] Replace searching events with "search mutator" callbacks

**Reviewers should focus on:**
- Should each model's gambit registration be moved to the appropriate service provider?
- Should the explicit ID list used in ListPostsController be accomodated by the AbstractSearcher? If so, should other filters apply here, or should only the ID list be used?
- Should we change how we accept search queries? e.g. sending them as JSON instead of CSV to begin with? For example, filter parameters could be sent separately.
- Do we need to support compat for ConfigurePostsQuery no longer being functional? It's going to be a pain/very hacky to get it to work with the refactor, and I was unable to find any extensions other than tags and mentions (which we have control over) using them? Given the work needed, and potential issues involved in, supporting it, and considering that the impact would be extremely minimal, I think this would be a justifiable breaking change.
- Franz, does this more-or-less move towards your vision for the search API?

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).

### CODE REVIEW

**Comment by franzliedke** [comment]
Because we now [auto-format our JS code with Prettier](https://discuss.flarum.org/d/23464-js-code-is-now-auto-formatted-with-prettier), this branch now has conflicts with `master`. Sorry about that. :wink: 

Please take the [steps outlined in the forum](https://discuss.flarum.org/d/23464-js-code-is-now-auto-formatted-with-prettier/2) to resolve the conflicts.

**Comment by askvortsov1** [comment]
I updated the extender name to FlarumSearch, so that we can use Search for the extender that will manage search drivers. That way, we can merge this, and proceed with further PRs as the discussion in https://github.com/flarum/core/issues/1355 evolves.

**Comment by franzliedke** [comment]
We'll revisit this for Beta 15. I like that this makes the `ConfigurePostTypes` event obsolete, as far as I can tell.

**Comment by askvortsov1** [comment]
We might want to consider moving whereVisibleTo checks after gambits to ensure that filtering doesn't accidentially expose content that should not be exposed. If that has performance implications on the full text search, I think we should call gambits and full text search separately with `whereVisibleTo` in between.

Also, if we want to keep the Searching events, we should provide them with the full Eloquent builder, not just the query builder.

**Comment by askvortsov1** [comment]
Aside from comments on implementation, the main thing we need to figure out here is whether we want to make any changes to these APIs so that https://github.com/flarum/core/issues/1355 minimizes breaking changes. Some ideas:

- Should we pass in the full Eloquent query object to gambits?
- Should we get a full list of gambits that will be run before they are actually run, so that gambits can be aware of other gambits?
- Could we add an object/array to AbstractSearch that gambits could modify to add data about what they're filtering, and which could be assembled/applied in the full text gambit (as suggested in https://github.com/flarum/core/issues/1355#issuecomment-719970809)
- Would operations on other search drivers use a different extender, or the same one? If so, we should rename this extender to `Search`, and initialize it with an argument, which is a string identifier for the driver in question.
- We might want to separate the "full text gambit" from the rest of the gambits, and treat it as its own operation. Or at least rename it since "full text" is an implementation name for MySQL?
- We might want to provide the full text gambit with info about sort, offset, limit, etc if those are (at least partially) handled by the search engine being used.

**Review by luceos — CHANGES_REQUESTED** [review]
This PR is so massive, it's insane. This needs to be well tested.

- deprecated messages need to be updated (beta 13 => beta 15)
- issue has to be created to remove the hacky temporary workaround

I left one comment where you've used raw queries. Raw queries are exceptionally risky, try to refrain from using them too much.

**Comment by askvortsov1** [comment]
Since we've changed our mind on how we want to approach this a bit, I'm going to close it, but then use pieces from it in other PRs.

**Pull request closed without merging**
