### PR TITLE
feat(mentions,tags): tag mentions

### LINKED ISSUE #3693: [Mentions] 3 characters hex color and `isDark` util: `Unsupported operand types: string + string`
### Current Behavior

Mentioning a group which has been set up with a 3 characters hex color brings an error when you try to mention it: `TypeError: Unsupported operand types: string + string in /var/www/flarum2.localhost/PATH_TO_MONOREPO/extensions/mentions/src/ConfigureMentions.php:208`

### Steps to Reproduce

1. Set up a group with a 3 char hex color (e.g. `#CCC`)
2. Mention this group in a conversation

### Expected Behavior

The 3 char. hex color should be converted to a 6 char. hex color in order to being parsed in the `isDark` util

### Screenshots

_No response_

### Environment

- Flarum version: main branch
- local dev env

### Output of `php flarum info`

_No response_

### Possible Solution

The original javascript `isDark` util is working fine. This is the [php implementation](https://github.com/flarum/framework/blob/67dd2c21b6c2a2b1bde948015edd0f5a51569229/extensions/mentions/src/ConfigureMentions.php#L194-L218) for Mentions which is in cause:

```php
        $hexNumbers = Str::replace('#', '', $hexColor);
        if (Str::length($hexNumbers) === 3) {
            $hexNumbers += $hexNumbers;
        }
```

should be:

```php
        $hexNumbers = Str::replace('#', '', $hexColor);
        if (Str::length($hexNumbers) === 3) {
            $hexNumbers = $hexNumbers . $hexNumbers;
        }
```

### Additional Context

_No response_

### LINKED ISSUE #3725: User mention not rendered in post preview when editing a message and when the user is not cached in the store
### Current Behavior

When editing a message that contains a user mention, and when the user is not cached in the store, the mention is not rendered in post preview.

### Steps to Reproduce

1. refresh the page to make sure the store is cleared
2. edit a message that contains a mention to a user
3. see in the preview that the mention is not rendered

Then:

4. click the user name in the mention, see that the pop up box opens and shows the name of this user
5. modify any part of the post
6. see that the preview is now updated with the correctly rendered user mention

### Expected Behavior

The user mention should always look in the preview the way they will be seen once posted.

### Screenshots

Peek 2023-01-31 13-53

### Environment

- Flarum version: 1.6.2
- Website URL: localhost
- Webserver: PHP built-in web server
- Hosting environment: local
- PHP version: 8.2.1 (cli) (built: Jan  6 2023 15:12:40) (NTS)
- Browser: Mozilla Firefox 109.0

### Output of `php flarum info`

```
Flarum core 1.6.2
PHP version: 8.2.1
MySQL version: 10.6.11-MariaDB-2
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, random, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, intl, exif, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, Zend OPcache, xdebug
+----------------------+---------+--------+
| Flarum Extensions    |         |        |
+----------------------+---------+--------+
| ID                   | Version | Commit |
+----------------------+---------+--------+
| flarum-flags         | v1.6.1  |        |
| flarum-approval      | v1.6.1  |        |
| flarum-tags          | v1.6.1  |        |
| flarum-suspend       | v1.6.1  |        |
| flarum-subscriptions | v1.6.1  |        |
| flarum-sticky        | v1.6.1  |        |
| flarum-statistics    | v1.6.1  |        |
| flarum-mentions      | v1.6.1  |        |
| flarum-markdown      | v1.6.1  |        |
| flarum-lock          | v1.6.1  |        |
| flarum-likes         | v1.6.1  |        |
| flarum-lang-french   | v4.4.0  |        |
| flarum-lang-english  | v1.6.0  |        |
| flarum-emoji         | v1.6.1  |        |
| flarum-bbcode        | v1.6.0  |        |
+----------------------+---------+--------+
Base URL: http://localhost:8080
Installation path: /home/nicolas/Source/www/flarum
Queue driver: sync
Session driver: file
Mail driver: smtp
Debug mode: ON
```

### Possible Solution

This could make use of an API that allows to refresh the composer preview as described in https://github.com/flarum/framework/issues/3720.

I solved this problem in my extension by making a store call in the TextFormatter filter's JS part, then refreshing the preview once the promise resolved: https://github.com/club-1/flarum-ext-cross-references/pull/7/files#diff-0fa1a002dc778d61dfd77c836df026dc259755459ef9417ad12450569c211388

Thus, it looks very strange in the preview when the mention is not rendered correcly:
Peek 2023-01-31 14-12

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by SychO9**
**Also Closes #3725**
**Also Closes #3693**

**Changes proposed in this pull request:**
* Refactors JS autocomplete code to allow easily adding different mention formats and different mentionable models. Notably, we now have the interfaces `MentionableModel` and  `MentionFormat`.
* Adds tags search on the tags API list endpoint.
* Adds tag mentions tests.
* Adds a tag mention feature using the format: `#slug` since the slug is unique.
* Adds tag mention stying.
* Fixes [unauthorized mention of hidden groups](https://github.com/flarum/framework/commit/2d7b23da866f8cfe18ed827a1d013034b77eb032).
* Makes sure the mentions extension works with and without the tags extension installed/enabled.

**Reviewers should focus on:**
* The actual `post_mentions_tag` table migration resides i the tags extension whereas the rest of the tag mention logic resides in the mentions extension. This is done for the following reasons:
  * It shouldn't matter because by 2.0 we will have a polymorphic backend implementation of mentionable models, in which case this table will be dropped anyway.
  * Even if the mentions extension isn't used, the existence of the table does not add inconvenience.
  * There is a very good chance we will use this table to fix (https://github.com/flarum/issue-archive/issues/44) as part of tags anyway, in which case it would make sense to have it in tags.
* The mentions extension introduces an extension API to easily add new mention formats and new mentionable models, for example, if I was building a discussion mention extension that used a format of `!id`:
```ts
return [
  new Extend.Mentionables()
    .format(ExclamationFormat)
    .mentionable('!', DiscussionMention),
];
```

**Screenshot**
[Screencast from 03-13-2023 10:45:59 AM.webm](https://user-images.githubusercontent.com/20267363/226129858-d1082109-f072-407d-9187-5e557c85a033.webm)

**Necessity**

- [x] Has the problem that is being solved here been clearly explained?
- [x] If applicable, have various options for solving this problem been considered?
- [x] For core PRs, does this need to be in core, or could it be in an extension?
- [x] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).
- [x] Core developer confirmed locally this works as intended.
- [x] Tests have been added, or are not appropriate here.

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

### CODE REVIEW

**Review by luceos — APPROVED** [review]
This works as intended, but is there a way to use routing instead of a href link?

**Comment by davwheat** [comment]
Without that, the linking wouldn't be accessible to screenreaders, nor indexable by search engines, though?

**Comment by SychO9** [comment]
> Without that, the linking wouldn't be accessible to screenreaders, nor indexable by search engines, though?

It shouldn't be the case, the code already uses a click event use the mithril routing for user and post mentions.

**Comment by luceos** [comment]
I'd be okay for this to be merged for v1.8, we can properly test this in QA. In fact we should update our PR template to include a checklist item for "Provide steps to properly test this functionality still works during QA" (on it)

**Review by imorland — APPROVED** [review]

**Pull request merged**
