### PR TITLE
feat: Delete all notifications

### PR DESCRIPTION
**Pull request by imorland**
Recreates https://github.com/flarum/framework/pull/3205

**Changes proposed in this pull request:**
Using the existing convention for marking all notifications as read, this PR proposes an additional option to delete all notifications as well.

Additionally, adds a `Tooltip` to the existing Mark as Read button for better clarity

**Reviewers should focus on:**

**Screenshot**
image
image

image
image

**Necessity**

- [ ] Has the problem that is being solved here been clearly explained?
- [ ] If applicable, have various options for solving this problem been considered?
- [ ] For core PRs, does this need to be in core, or could it be in an extension?
- [ ] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

### CODE REVIEW

**Review by SychO9 — CHANGES_REQUESTED** [review]
Looks good, haven't tested locally yet. Can we add an integration test for this?

**Review by SychO9 — APPROVED** [review]

**Comment by SychO9** [comment]
re-review please :D

**Review by davwheat — APPROVED** [review]

**Comment by akarimi-com** [comment]
There is already an extension "https://packagist.org/packages/blomstra/notification-deleter" so we have to delete this extension right?
Because this feature will include in V1.5

**Comment by luceos** [comment]
> There is already an extension "https://packagist.org/packages/blomstra/notification-deleter" so we have to delete this extension right? Because this feature will include in V1.5

Yes, once v1.5 comes out the Blomstra extension will no longer be necessary and will be marked as abandoned.

**Comment by askvortsov1** [comment]
The two icons feel pretty close to me, is there a risk of people clicking the wrong one on small screens?

**Comment by SychO9** [comment]
the risk exists indeed.

**Comment by davwheat** [comment]
That's why there's a confirmation dialog, no?

**Comment by askvortsov1** [comment]
> That's why there's a confirmation dialog, no?

More margin looks cleaner IMO: https://github.com/flarum/framework/pull/3629

**Comment by matteocontrini** [comment]
Also, why was the "mark as read" button moved to the left? I keep clicking the wrong button on discuss...

**Comment by askvortsov1** [comment]
> Also, why was the "mark as read" button moved to the left? I keep clicking the wrong button on discuss...

Reading from left to right, it makes sense for less "powerful" actions (e.g. marking as read) to preceed more powerful actions (e.g. deleting all notifs). I think that was the design intuition.

**Comment by davwheat** [comment]
I think my muscle memory will also catch me out here

**Pull request merged**
