### PR TITLE
Remove welcome banner feature

### PR DESCRIPTION
**Pull request by franzliedke**
The feature is very limited in scope, and we hope for community
extensions to take over this feature and make it much better.

**After merge:**
- [ ] Remove translations in flarum-ext-english (see flarum/flarum-ext-english#117)
- [ ] Remove usage of hero in flarum-ext-tags

### CODE REVIEW

**Comment by tobscure** [comment]
I will take care of the flarum-ext-tags changes if you don't mind :)

**Comment by franzliedke** [comment]
So far I only removed [this line](https://github.com/flarum/flarum-ext-tags/blob/43607b48a41b34c6fa10c2ad68c053b5bd2f0fc6/js/forum/src/components/TagsPage.js#L26).

**Comment by franzliedke** [comment]
@tobscure What's your status on this?

**Comment by tobscure** [comment]
Yeah I've got an idea of what I want to do, haven't started yet though

**Comment by ronnie-depp** [comment]
Welcome Banner feature is good so far for users of flarum like me.
Is the decision to remove the feature based on user requests/feedback?

I suggest giving the option to retain the feature or overridden by extension to transform it to anything like Header Slider plugin/extension or any customized header option.

**Comment by ronnie-depp** [comment]
can I say that welcome banner is a nice feature that I love.
where can i discuss about it that what will eventually become of this?
will it be totally eliminated without a chance to retain it or removed with a well thought out alternative-extended by community extensions to customize the header area along with the option to rebuild the welcome banner via custom extension?

**Comment by franzliedke** [comment]
@ronnie-depp We feel this feature is better suited for a more advanced solution in extension space. 😄

**Comment by webagil-kevin** [comment]
"Remove usage of hero in flarum-ext-tags" (see [Discussion page design tweaks flarum/framework#43](https://github.com/flarum/flarum-ext-tags/pull/43)

**Comment by webagil-kevin** [comment]
Conflict file "js/forum/src/components/WelcomeHero.js" is with [FontAwesome v5.0.6 flarum/framework#1372](https://github.com/flarum/core/pull/1372). You must delete the file.

**Comment by TurboProgramming** [comment]
Do we have any updates on this?

Need any help?

I also see that this PR is waiting this PR's merge: https://github.com/flarum/flarum-ext-english/pull/117

**Comment by TurboProgramming** [comment]
I'm also aware that this is for Beta 9, but if there is something I can help, we may complete this for Beta 8.

**Comment by luceos** [comment]
@TurboProgramming thank you for jumping in, please understand that we are moving forward based on a carefully planned roadmap. The welcome banner is planned to be removed in beta 9, this keeps the list of backward breaking changes understandable as they are already huge for beta 8 as is. We also need a replacement extension to pick up existing configurations before we abandon the functionality in core.

If you'd like to contribute feel free to pick up anything else.

**Comment by TurboProgramming** [comment]
Thanks, @luceos, I will try my best. Sorry for the distraction.

**Comment by franzliedke** [comment]
I rebased this and fixed the conflicts. Will leave the rest to @tobscure.

**Comment by PeopleInside** [comment]
Please ... I hope before remove this will be released an extension that allow to not miss this.

**Comment by luceos** [comment]
Delaying until after stable.

**Comment by franzliedke** [comment]
I created flarum/issue-archive#239 to track the extraction into a new extension. This PR is already out-of-date and will only gather more conflicts until it is time to tackle this. It will be easy enough to do from scratch, so I am closing this and assigning the ticket to the milestone.

**Pull request closed without merging**
