### PR TITLE
fix(mentions): mentions keep firing after a reply

### LINKED ISSUE #3766: Mentions fire xhr after completing the mentions element
### Current Behavior

When you mention someone (perfectly visible when using "reply") and you continue typing after that, by dividing the mention and the rest of your text with a space, XHR's keep firing continuously. This causes a huge overload on the server.

### Steps to Reproduce

1. Reply to a post
2. Continue typing a reply
3. Inspect network tab

### Expected Behavior

No XHR should be fired after the mention block is finished.

### Screenshots

image

### Environment

- Flarum version: 1.7.1 and nightly
- Website URL: http://discuss.flarum.org and nightly.flarum.org

### Output of `php flarum info`

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by luceos**
**Fixes #3766**

**Changes proposed in this pull request:**

Identify whether we have a completed mention before the current text so that we can stop mentioning. The logic checks for any space and/or follow up text, then also check whether the display name mention exists.

**Reviewers should focus on:**

Did I forget about any edge cases?
Are we okay with this if statement? Imo it increases readability wdyt?

**Screenshot**

**Necessity**

- [ ] Has the problem that is being solved here been clearly explained?
- [ ] If applicable, have various options for solving this problem been considered?
- [ ] For core PRs, does this need to be in core, or could it be in an extension?
- [ ] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

### CODE REVIEW

**Comment by garygreen** [comment]
> We cancel searching when we see a space or newline

It should probably stop searching also whenever a non-valid username character is pressed. E.g. consider if you typed:

```
@luceos.
```

When typing "." to end the sentence it should stop firing. It looks like this is already the case for mentions package - it will show dropdown immediately on typing of `@` and then any characters like `. , @ -` it will close the dropdown and stop autocompleting. How does that logic work? Would it be easier to hook into a `close` event of some kind for the mentions extension?

**Comment by luceos** [comment]
> It should probably stop searching also whenever a non-valid username character is pressed

The mentions extension also supports display names though. Those can be anything, even UTF8 characters.

**Comment by luceos** [comment]
@SychO9 can you look at this one, especially now that I'm reviewing #3769 this "bug" becomes a nuisance.

**Comment by SychO9** [comment]
will look into it after #3769 is merged as it reactors this part of the code completely

**Comment by SychO9** [comment]
Superseded by #3806

**Pull request closed without merging**
