### PR TITLE
feat: improve emoji autocomplete

### PR DESCRIPTION
**Pull request by SychO9**
**Changes proposed in this pull request:**
* The current emoji autocomplete opens up by default by listing the first items on the emoji map from the cdn.
* This PR make it so that the common smileys are listed by default.
* This PR also improves the emoji autocomplete UX.

**Before**
image

**After**
image
image

**Necessity**

- [x] Has the problem that is being solved here been clearly explained?
- [x] If applicable, have various options for solving this problem been considered?
- [x] For core PRs, does this need to be in core, or could it be in an extension?
- [x] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).
- [x] Core developer confirmed locally this works as intended.
- [x] Tests have been added, or are not appropriate here.

### CODE REVIEW

**Comment by dsevillamartin** [comment]
Could it be made so the name of the currently selected icon shows up in either placeholder or a tooltip? That way the name can be learned, as otherwise one would need to guess or keep selecting from the autocomplete every time. I see the `alt` attribute on the image, not sure if anything else would be better or helpful. Just a thought.

Otherwise, I like the changes! :+1:

**Comment by SychO9** [comment]
@dsevillamartin it also has tooltips if that's you mean

image

**Comment by dsevillamartin** [comment]
@SychO9 Oh, I did not see the code. Forgot how tooltips worked nowadays for a sec. :+1:

**Review by imorland — APPROVED** [review]

**Comment by imorland** [comment]
@SychO9 if you can take care of the conflict, this is ready to merge :)

**Comment by orschiro** [comment]
Quick question to this. When will this improvement be available?

Can anyone give me a rough date estimate?

I am wondering because this merge has been completed in Nov 23, and we are now in almost 2025.

Thanks!

**Comment by SychO9** [comment]
It's part of 2.0, so when the ***stable*** release of 2.0 is ready. We can't know when that will be.

**Comment by orschiro** [comment]
Thanks! But roughly?

Will it be months or rather years?

**Comment by SychO9** [comment]
Hopefully months

**Comment by orschiro** [comment]
Understood, thanks!

And why is it not possible to squeeze in this improvement with a minor
release?

Sami Mazouz ***@***.***> schrieb am So., 8. Dez. 2024, 09:10:

**Pull request merged**
