### PR TITLE
Unicode user names are supported

### PR DESCRIPTION
**Pull request by SeRazon**
**Fixes #0000**

**Changes proposed in this pull request:**

**Reviewers should focus on:**

**Screenshot**

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).

### CODE REVIEW

**Comment by askvortsov1** [comment]
Hi! Thank you for the PR, but this is an issue where the decision has already been made. See https://github.com/flarum/core/issues/557 and linked issues for a lot of discussion. The tl;dr is that unicode usernames open a lot of rabbit holes leading to matters out of our control (like URL encoding) that could cause unexpected issues and user-side confusion. 

The solution introduced in https://github.com/flarum/core/issues/2230 is using https://github.com/flarum/nicknames, possibly in conjunction with an ID or nickname based model slug driver. Unfortunately, this means that we won't be merging a change like this at this time (although we might be open to smaller changes with discussion, like allowing periods ala flarum/framework#2529),

Going forward, if there isn't already an issue discussing an issue with proposed implementation, opening an issue to discussed things like this before proceeding to PR could help avoid confusion. Thank you again for the PR, sorry that we won't be able to make this change.

**Comment by SeRazon** [comment]
> 你好！感谢您的公关，但这是已经做出决定的问题。有关大量讨论，请参见[＃557](https://github.com/flarum/core/issues/557)和链接的问题。tl; dr是unicode用户名打开了很多麻烦，导致了我们无法控制的问题（例如URL编码），可能会导致意外问题和用户端混乱。
> 
> [＃2230中](https://github.com/flarum/core/issues/2230)引入的解决方案使用https://github.com/flarum/nicknames，可能与基于ID或昵称的模型slug驱动程序结合使用。不幸的是，这意味着我们目前不会合并这样的更改（尽管我们可能会在讨论中接受较小的更改，例如允许使用句点ala [＃2529](https://github.com/flarum/core/pull/2529)），
> 
> 展望未来，如果讨论拟议实施中的问题尚不存在问题，则在进行PR之前开放一个问题以讨论此类问题可以避免混淆。再次感谢您提供公关，对不起，我们将无法进行此更改。



> Hi! Thank you for the PR, but this is an issue where the decision has already been made. See flarum/framework#557 and linked issues for a lot of discussion. The tl;dr is that unicode usernames open a lot of rabbit holes leading to matters out of our control (like URL encoding) that could cause unexpected issues and user-side confusion.
> 
> The solution introduced in flarum/issue-archive#203 is using https://github.com/flarum/nicknames, possibly in conjunction with an ID or nickname based model slug driver. Unfortunately, this means that we won't be merging a change like this at this time (although we might be open to smaller changes with discussion, like allowing periods ala flarum/framework#2529),
> 
> Going forward, if there isn't already an issue discussing an issue with proposed implementation, opening an issue to discussed things like this before proceeding to PR could help avoid confusion. Thank you again for the PR, sorry that we won't be able to make this change.

Try CJK?
change to
 'regex:/^[-_a-zA-Z0-9\x7f-\xff]*[-_a-zA-Z\x7f-\xff][-_a-zA-Z0-9\x7f-\xff]*$/i'

**Comment by askvortsov1** [comment]
Wouldn't all the URL encoding issues still be present?

The core team is generally hesitant to introduce new bundled extensions, but nicknames was created specifically to address this issue. Are there reasons why it's not working for you?

**Comment by StarsRivers** [comment]
> Wouldn't all the URL encoding issues still be present?
> 
> The core team is generally hesitant to introduce new bundled extensions, but nicknames was created specifically to address this issue. Are there reasons why it's not working for you?

Most users of the website use Chinese, but they are prompted to register in Chinese. 

Or... allow both user name and nickname to be set when registering?

**Comment by askvortsov1** [comment]
Sorry for the delayed response, this got lost in my notifications

> Or... allow both user name and nickname to be set when registering?

I think this feature would make sense to have in the extension. Additionally, the username could be hidden completely and generated as a random string / number. Would you be able to open an issue about this?

**Comment by SeRazon** [comment]
> 抱歉，回复延迟，这在我的通知中丢失了
> 
> > 还是...在注册时允许同时设置用户名和昵称？
> 
> 我认为此功能在扩展中将是有意义的。此外，用户名可以完全隐藏并生成为随机字符串/数字。您能对此提出一个问题吗？



> Sorry for the delayed response, this got lost in my notifications
> 
> > Or... allow both user name and nickname to be set when registering?
> 
> I think this feature would make sense to have in the extension. Additionally, the username could be hidden completely and generated as a random string / number. Would you be able to open an issue about this?

OK

**Pull request closed without merging**
