### PR TITLE
Add group gambit to support search user by group name

### PR DESCRIPTION
**Pull request by liji**
Add group gambit to support search user by group name

- `/api/users?filter[q]=group:admin`

- `/api/users?filter[q]=group:admin,mod`

refer to flarum/issue-archive#418

### CODE REVIEW

**Review by tobyzerner — APPROVED** [review]
Looks good!

I think there are possibly a few tweaks we could make to improve performance (a subquery perhaps?) but that is also the case for a lot of other gambits + the fulltext search driver, so maybe we'll do all that optimization all together at a later date.

**Comment by dav-is** [comment]
Laughed a bit at the typical styleci struggle

**Comment by liji** [comment]
Yes, I agree, there are things we can do to improve the performance.

**Comment by Luceos** [comment]
@tobscure you might consider putting styleci to auto patch any merge. That resolves a lot of issues contributors might have. The time they now spend on fixing styleci compliance can be used to send in another PR :smile:

**Comment by franzliedke** [comment]
@liji Thank you very much for the implementation and your patience! 👍

**Pull request merged**
