### PR TITLE
perf: transpile js to es6

### PR DESCRIPTION
**Pull request by davwheat**
**Changes proposed in this pull request:**

- output ES6 Javascript instead of ES5

**All extension JS source code will need to be recompiled with an updated Webpack config.**

This will reduce our tech debt and overall bundle size due to unneeded ES5 polyfills included by Babel despite us not supporting any ES5 browsers.

**Necessity**

- [x] Has the problem that is being solved here been clearly explained?
- [x] If applicable, have various options for solving this problem been considered?
- [x] For core PRs, does this need to be in core, or could it be in an extension?
- [x] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).
- [x] Core developer confirmed locally this works as intended.
- [x] Tests have been added, or are not appropriate here.

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

### CODE REVIEW

**Comment by SychO9** [comment]
@davwheat is this complete?

**Comment by davwheat** [comment]
Yeah, I think so. I only marked it as draft because we weren't 2.x-dev ready then.

**Review by SychO9 — APPROVED** [review]

**Pull request merged**
