### PR TITLE
chore: corrected typos in routes comments

### PR DESCRIPTION
**Pull request by JamesShaver**
Corrected typos in the comments

**Fixes #0000**

**Changes proposed in this pull request:**

**Reviewers should focus on:**

**Screenshot**

**QA**

**Necessity**

- [ ] Has the problem that is being solved here been clearly explained?
- [ ] If applicable, have various options for solving this problem been considered?
- [ ] For core PRs, does this need to be in core, or could it be in an extension?
- [ ] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

### CODE REVIEW

**Review by askvortsov1 — APPROVED** [review]
Do we need all these comments? Feels like the code is fairly self explanatory

**Comment by JamesShaver** [comment]
> Do we need all these comments? Feels like the code is fairly self explanatory

The code comments show up in IDEs, so I would say yes each method needs to be commented accurately.

**Comment by davwheat** [comment]
If they were function definitions, sure. I don't oppose to any of these, though.

**Review by SychO9 — APPROVED** [review]
Thanks! I do agree with Sasha though, the code is readable enough not to need these comments.

**Pull request merged**
