### PR TITLE
Do not catch exceptions when testing Console commands

### PR DESCRIPTION
**Pull request by n-peugnet**
**Changes proposed in this pull request:**

Configure the ConsoleApplication to not catch exceptions when testing Console commands.

This allows to easily test a case where a command should throw using `$this->expectException()`.

**QA**
For now I only tested it locally by modifying the vendor directory. It should not cause too much issues for existing testing suites, except if the way to check if a console was throwing was done by checking the output. As it is rather tedious I don't suspect that there are a lot of such test cases.

Edit: well there is one here :sweat_smile: 
https://github.com/flarum/framework/blob/af3f91ca5b30c2bfc7a7f9dd36839339372cc745/framework/core/tests/integration/extenders/ConsoleTest.php#L22-L29

This case has been simple to test as there is no other input, and Symfony seems to treat this exception differently, as usually it shows the file name and line of the throw statement. It can be written equally simply using `$this->expectExceptionMessage()`.

Edit2: In fact I think this test would even be better off using `$this->expectException()` as the goal is not to check the message but that the command is not found, and because this way the test is less brittle.

**Necessity**

- [ ] Has the problem that is being solved here been clearly explained?
- [ ] If applicable, have various options for solving this problem been considered?
- [ ] For core PRs, does this need to be in core, or could it be in an extension?
- [ ] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

### CODE REVIEW

**Review by askvortsov1 — APPROVED** [review]
This feels like a good change to me, especially with that error message coming from a dependency. That being said, I wonder if it would make sense to have an additional test case that would switch "catch exceptions" back on, so we can ensure that the UX in case of an error is reasonable. Preferably, this would be a flarum-level exception, not something from Symfony.

**Comment by n-peugnet** [comment]
Please note that this is still a breaking change for the testsuites of extension developers, and it should be announced accordingly in the release notes.

**Comment by SychO9** [comment]
Thanks for the PR!

I think this should be included in 2.0 since it has non BC changes.

**Comment by askvortsov1** [comment]
Fair enough. I'm generally much less concerned about testing/static analysis breaking changes than user-facing ones, but since this isn't a very urgent change, 2.0 makes sense.

**Review by imorland — APPROVED** [review]

**Pull request merged**
