### PR TITLE
docs: ItemList set methods throw errors when keys are not present

### PR DESCRIPTION
**Pull request by davwheat**
**Changes proposed in this pull request:**

- Corrects errors in TSDoc annotations of ItemList

**Reviewers should focus on:**

N/A

**Necessity**

- [x] Has the problem that is being solved here been clearly explained?
- [x] If applicable, have various options for solving this problem been considered?
- [x] For core PRs, does this need to be in core, or could it be in an extension?
- [x] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).
- [x] Core developer confirmed locally this works as intended.
- [x] Tests have been added, or are not appropriate here.

### CODE REVIEW

**Review by SychO9 — APPROVED** [review]

**Comment by imorland** [comment]
I'm personally in two minds about this.

I've been using these methods on the assumption that the docs are correct 🙈 , so part of me says that in the year that this has been released, the core behaviour should match the docs.

On the other side, throwing an error is helpful for tracking down typo's, etc

Thinking a while... 🤔

**Comment by davwheat** [comment]
I mean we *could* ignore missing keys in prod, and error in dev?

**Review by askvortsov1 — APPROVED** [review]

**Comment by askvortsov1** [comment]
> I mean we _could_ ignore missing keys in prod, and error in dev?

I believe we have a helper for this?

**Comment by davwheat** [comment]
> I believe we have a helper for this?

Indeed we do! It's just a case of if it's worthwhile doing so.

**Pull request merged**
