### PR TITLE
Add page separators and load previous button to DiscussionList

### PR DESCRIPTION
**Pull request by dsevillamartin**
**Refs #2781**

https://user-images.githubusercontent.com/6401250/117724452-c2c5c200-b1b1-11eb-9bb6-4c49cd28849c.mp4

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.

**Required changes:**

- [ ] Related core extension PRs: (Remove if irrelevant)

### CODE REVIEW

**Review by askvortsov1 — CHANGES_REQUESTED** [review]
Could we use anchorScroll so it doesn't jump through the prev loaded page?

**Comment by datitisev** [comment]
> Could we use anchorScroll so it doesn't jump through the prev loaded page?

I just tried to do so, but it doesn't work as `anchorScroll` simply runs the `callback()` expecting functionality to be synchronous. As `loadPrev` is asynchronous (Promise), it doesn't work...

I tried adding it manually after the promise remained, but wasn't able to get it quite right - I'm not very good at this scroll stuff. I also don't think it's necessarily a good idea either, because as `m.redraw()` is called within `PaginatedListState`, the user could've scrolled away from between before calling the Promise & after it is resolved.

**Comment by davwheat** [comment]
Can we use the `display=block` on the spinner instead of manually setting the height?

**Comment by datitisev** [comment]
> Can we use the display=block on the spinner instead of manually setting the height?

This wouldn't change the height as far as I'm aware? The reason that CSS rule was added was to occupy around the same amount of space as the button iirc.

**Comment by davwheat** [comment]
[It would](https://github.com/flarum/core/blob/d1e38558c5a0bab54babd3c62a85a93d1a63e0ad/less/common/LoadingIndicator.less#L47), but now I look at it, it might be too tall.

**Comment by datitisev** [comment]
@davwheat Oh, I thought you meant simply `display: block;` CSS, not an attribute on the `<LoadingIndicator />` component.

**Comment by davwheat** [comment]
I wish I picked a better name for that attr now 😅

**Comment by askvortsov1** [comment]
Hello, thank you for your pull request! In order to speed up future development, keep all work in one place, and take advantage of CI tools that can help us avoid breaking changes, we have moved all Flarum code to a single monorepo at [flarum/framework](https://github.com/flarum/framework). You can read more about this process [in our dev diary](https://discuss.flarum.org/d/29894-dev-diary-build-20/3). Unfortunately, pull requests can't be carried over to the monorepo, so we have to close all open pull requests. If this pull request is still relevant, please feel free to reopen it over on the monorepo. We apologize for the inconvenience, and hope you will consider contributing to Flarum again in the future.

**Pull request closed without merging**
