### PR TITLE
Make interval between posts configurable

### LINKED ISSUE #302: Wait time between creating discussions/posts
## Explanation

Currently, there is no way to set a limit on the time to wait for new discussions/posts to be made by users. I searched through the code and found that the floodgate class has a hard-coded time value of -10  seconds/minutes. I know this can be extended and used to create an extension that can handle this issue, but I honestly believe that this should be a setting that is included in core itself.

[This line is where I found the hard-coded value.](https://github.com/flarum/core/blob/2140619c0ba619602b90ef9526b1278335f7f3d8/src/Core/Post/Floodgate.php#L38)

This should be a permission-based setting that is set as an input rather than a drop-down with just a set amount (10 seconds/minutes) seems to be the natural flow here for some reason).

## Technical details

- Version of Flarum: v0.1.0-beta.7
- Website URL where the bug is visible: N/A
- The webserver you are running: N/A
- PHP version: N/A
- Hosted environment: N/A
- Hosting provider: N/A

## Flarum info

```
N/A
```

## Log files

```
N/A
```

### LINKED ISSUE #1302: Wait time between creating discussions/posts
## Explanation

Currently, there is no way to set a limit on the time to wait for new discussions/posts to be made by users. I searched through the code and found that the floodgate class has a hard-coded time value of -10  seconds/minutes. I know this can be extended and used to create an extension that can handle this issue, but I honestly believe that this should be a setting that is included in core itself.

[This line is where I found the hard-coded value.](https://github.com/flarum/core/blob/2140619c0ba619602b90ef9526b1278335f7f3d8/src/Core/Post/Floodgate.php#L38)

This should be a permission-based setting that is set as an input rather than a drop-down with just a set amount (10 seconds/minutes) seems to be the natural flow here for some reason).

## Technical details

- Version of Flarum: v0.1.0-beta.7
- Website URL where the bug is visible: N/A
- The webserver you are running: N/A
- PHP version: N/A
- Hosted environment: N/A
- Hosting provider: N/A

## Flarum info

```
N/A
```

## Log files

```
N/A
```

### PR DESCRIPTION
**Pull request by timozander**
**Fixes flarum/issue-archive#302**

**Changes proposed in this pull request:**
- Add `post_flood_interval` setting to manually configure the interval users have to wait before posting again
- Add integration tests for both this feature and flarum/framework#1938 
- Add `Advanced` settings page with a `Security` section to contain this and possibly further settings 

**Reviewers should focus on:**
Use of Mockery: It was already required but hasn't been used anywhere else. I didn't found any guidelines regarding this.

**Screenshot**
flarum_advanced_settings

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).

**Required changes:**

- [ ] Related core extension PRs: [flarum/lang-english](https://github.com/flarum/lang-english/pull/161)

### CODE REVIEW

**Comment by askvortsov1** [comment]
You're going to want to rebase and adjust the unit tests, we've been moving them away from the old controller test style to more accurately model real interactions with the site

**Comment by askvortsov1** [comment]
I like the ability to configure flood time! However, I think that some discussion as to the 'Advanced' page is warranted to make sure that the core team wants it. I personally think it's a good idea, but it might also encourage disorganized grouping of settings.

**Comment by timozander** [comment]
Definitely! I was also a little hesitant with that one. I could imagine to group _Permissions_ and this one into some kind of _Security_ tab

I'll adjust the tests

**Comment by timozander** [comment]
I rebased and changed the test accordingly

**Comment by clarkwinkelmann** [comment]
What happened to the diff of this PR ? Seems like the merge/rebase didn't work as expected.

I have trouble decrypting what was actually added by the PR.

Based on the original post, I don't think naming a dashboard tab "advanced" makes sense. It's just like calling it "miscellaneous", it does not indicate any purpose and would just become an excuse to not organize settings properly.

For these kind of settings, I'd recommend making them extendable, and then use another extension (third-party at first) to make them customizable. That way "time between posts" can become a setting inside an extension's settings modal.

**Comment by askvortsov1** [comment]
Yeah it looks like you might have accidentally merged instead of rebasing.

I agree with making stuff like this extendable, but I'm also not sure that just because it doesn't fit into the admin panes we have not means it should be an extension feature: ie, I don't think that the criteria we use to determine what should and shouldn't be an extension should be how it fits into the admin UI. For this case I think it's fine (the defaults will probably work for most people), but as a general practice I don't think that is how we should approach this issue. 

I think that the admin dashboard UX definitely needs to be revisited, but this is probably something that can wait past stable.

**Comment by timozander** [comment]
Yes, looks like I butchered the branch. I fixed that.

In my opinion, all built-in features should also be configurable using a vanilla Flarum installation. This is where my idea of "advanced" or "expert" settings originate from, suggesting that these settings are not meant for the 90% users but for those who want to excessively customize their installation.

Using an extension to configurate this built-in behaviour seems counter-intuitive for me.

**Comment by franzliedke** [comment]
Welcome @timozander and thanks for this awesome first contribution!

As you can see, we have a lot of open PRs currently. Our top goal right now is to keep our focus on the stable release, and [our planned path to get there](https://github.com/flarum/core/milestones).

As this issue (#1302) was originally planned for a later release, it might take a while until we get around to further reviews (and merging it). Now that so much work has already been done, that does not mean we cannot merge a good PR if we find the time, but I wanted to explain what we're trying to keep in mind when choosing what to review next, in order to avoid confusion or disappointment. We are trying hard not to get sidetracked in our focus, and our resources are limited.

Thanks for your understanding - and your contribution! :hugs:

**Comment by franzliedke** [comment]
Because we now [auto-format our JS code with Prettier](https://discuss.flarum.org/d/23464-js-code-is-now-auto-formatted-with-prettier), this branch now has conflicts with `master`. Sorry about that. :wink: 

Please take the [steps outlined in the forum](https://discuss.flarum.org/d/23464-js-code-is-now-auto-formatted-with-prettier/2) to resolve the conflicts.

**Comment by askvortsov1** [comment]
Despite the above comment, I'm going to close the above PR as part of our ongoing cleanup to reduce outdated issues/PRs. We're still very much interested in eventually having something like this though. Sorry again for the communication issues on our part.

**Pull request closed without merging**
