### PR TITLE
Inform users that some posts/discussions are withheld from the profile (#1006)

### PR DESCRIPTION
**Pull request by dav-is**
This is the best fix I could think of for flarum/issue-archive#321. Here are some screenshots:

discussions

discussions2

posts

Here is the PR for the translations: https://github.com/flarum/flarum-ext-english/pull/84

### CODE REVIEW

**Comment by franzliedke** [comment]
How do you like this UI, @tobscure?

**Comment by franzliedke** [comment]
Thanks for taking the time, @dav-is !

**Comment by dav-is** [comment]
It's my pleasure, @franzliedke

**Comment by tobyzerner** [comment]
Hmm I'm not convinced this is the most elegant solution to this problem. I know it's trying to explain to the user why the number may be wrong, but in doing so it kind of draws too much attention. You shouldn't know anything about posts that you can't see - even the fact that they exist, or who has been making them. But this kind of throws that in your face. It's a security issue.

Going to close this, let's go back to the drawing board in flarum/issue-archive#321. Thanks for the effort nonetheless @dav-is. As I mentioned elsewhere, reopening a dialogue in the issue to talk about the approach before sending a PR might be a good idea :)

**Comment by dav-is** [comment]
@tobscure I don't think it's a security issue. It tells you basically nothing about the missing posts, the number is generated simply by subtracting the number of posts displayed vs the count. Those posts could be deleted, hidden, or it simply be an error. I still believe the number should represent the actual number of posts and not the number the user can see. So I can't imagine a more elequent solution...

**Pull request closed without merging**
